apiVersion: v1
kind: ImageStream
metadata:
  labels:
    application: petclinc
  name: petclinc
  
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  labels:
    application: petclinic
  name: "petclinic" 
spec:
  runPolicy: "Serial" 
  triggers: 
    -
      type: "GitHub"
      github:
        secret: "secret101"
    - type: "Generic"
      generic:
        secret: "secret101"
    -
      type: "ImageChange"
  source: 
    git:
      uri: "https://github.com/nachomillangarcia/formadores-openshift.git"
    contextDir: spring-petclinic
  strategy:
    dockerStrategy:
      dockerfilePath: .
  output:
    to:
      kind: ImageStreamTag
      name: 'petclinc:latest'