kind: "BuildConfig"
apiVersion: "v1"
metadata:
  labels:
    application: todo
  name: "todo" 
spec:
  source: 
    git:
      uri: "https://github.com/nachomillangarcia/formadores-openshift.git"
    contextDir: java-app-todo-mysql
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'openshift/wildfly-101-centos7'
  output:
    to:
      kind: "DockerImage"
      name: "openshift-image-registry.image-registry.svc:5000/formadores/java-todo"

