apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo
spec:
    selector:
        matchLabels:
            app: todo
    template:
        metadata:
            labels:
                app: todo
        spec:
            containers:
            - name: todo
              image: nachomillangarcia/java-todo
              ports:
              - containerPort: 8080
              env:
              - name: DB_HOSTNAME
                value: mysql
              - name: DB_NAME
                value: todo
              - name: DB_USERNAME
                value: todo
              - name: DB_PASSWORD
                value: pass
              resources:
                requests:
                  cpu: 500m
                  memory: 1G
                limits:
                  cpu: 1
                  memory: 1.5G  
              livenessProbe:
                tcpSocket:
                  port: 8080
                initialDelaySeconds: 60
                periodSeconds: 10
                failureThreshold: 3
              readinessProbe:
                tcpSocket:
                  port: 8080
                periodSeconds: 10          
                  